# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c513ab4ac0b47e3afa3dd1db4b962835c54ef5e4404cff857faabd88ec0b66f14de005cde89a5bda5571e13d83629bdef88712e8629534d499f4d179111ebf7

test:
  secret_key_base: 17849c3ab5667c078b6cb3c5e3fc5a1d2afbd03c829ae568bf29b8693a06098ad7025787c1a6901eb568ff9bd85950ef0ee89962a9783b1fe0fdfeeb0f3f102f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
